-- Part 1 forensic rescan: the measurements of the original database and data
-- integrity report, re-taken read-only. Run with:
--   node scripts/ops/db.mjs --file scripts/ops/part1-rescan.sql
set default_transaction_read_only = on;

select metric, value from (
  -- Inventory
  select 1 o, 'tables (public)' metric, count(*)::text value from pg_class where relnamespace='public'::regnamespace and relkind in ('r','p')
  union all select 2, 'tables without a primary key', count(*)::text from pg_class c where c.relnamespace='public'::regnamespace and c.relkind='r' and not exists (select 1 from pg_constraint k where k.conrelid=c.oid and k.contype='p')
  union all select 3, 'foreign keys (all / not validated)', count(*)::text || ' / ' || count(*) filter (where not convalidated)::text from pg_constraint where contype='f' and connamespace='public'::regnamespace
  union all select 4, 'triggers disabled', count(*)::text from pg_trigger t join pg_class c on c.oid=t.tgrelid where not t.tgisinternal and t.tgenabled='D' and c.relnamespace='public'::regnamespace
  union all select 5, 'definer functions without fixed search_path', count(*)::text from pg_proc where pronamespace='public'::regnamespace and prosecdef and not exists (select 1 from unnest(coalesce(proconfig,'{}')) x where x like 'search_path=%')
  -- Security
  union all select 10, 'anon-callable definer functions that write with no caller check', count(*)::text from pg_proc p where p.pronamespace='public'::regnamespace and p.prosecdef and p.prorettype <> 'trigger'::regtype and has_function_privilege('anon', p.oid, 'execute') and p.prosrc ~* '(insert\s+into|update\s+[a-z_\.]+\s+set|delete\s+from)' and p.prosrc !~* '(auth\.uid\(\)|auth\.role\(\)|has_role|is_platform_operator|mm_is_operator|_operator\(\)|is_admin|_is_finance\(\)|current_setting\(.request\.jwt|has_permission|is_participant)' and p.proname not in ('mm_qr_scan','product_qr_register_scan','mm_short_link_resolve','mm_sandbox_activity','sf_faqs','mm_product_rating_refresh','mm_submission_risk_refresh')
  union all select 11, 'anon-writable tables without RLS', count(*)::text from pg_class c where c.relnamespace='public'::regnamespace and c.relkind='r' and not c.relrowsecurity and (has_table_privilege('anon', c.oid, 'insert') or has_table_privilege('anon', c.oid, 'update') or has_table_privilege('anon', c.oid, 'delete'))
  union all select 12, 'C2/C3/H1/H2 functions anon can execute', count(*)::text from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('mm_notify','reseller_commissions_reverse','reseller_commissions_for_order','influencer_commissions_for_order','mm_issue_for_order','founder_memory_record','founder_memory_retract','fa_agent_run_open','fa_agent_run_close','fa_agent_run_reap','founder_incident_claim','founder_purge_check_healing','founder_purge_check_decision','founder_purge_check_learning','influencer_tier_evaluate') and has_function_privilege('anon', p.oid, 'execute')
  union all select 13, 'H12 demo_intake_batches: RLS on / anon select', (select relrowsecurity::text from pg_class where oid='public.demo_intake_batches'::regclass) || ' / ' || has_table_privilege('anon','public.demo_intake_batches','select')::text
  -- Payments and orders
  union all select 20, 'orders by status', (select string_agg(status || '=' || n, ', ' order by status) from (select status, count(*) n from marketplace_orders group by 1) x)
  union all select 21, 'H3 orders in a status the CHECK forbids', count(*)::text from marketplace_orders where status not in ('pending_payment','paid','processing','fulfilled','completed','cancelled','refunded','disputed')
  union all select 22, 'H4 order status transition guard installed', (select count(*)::text from pg_trigger where tgname='marketplace_order_status_guard' and tgenabled='O')
  union all select 23, 'H5 paid orders without a payment intent (historical seeded)', count(*)::text from marketplace_orders o where o.status='paid' and not exists (select 1 from marketplace_payment_intents i where i.order_id=o.id)
  union all select 24, 'H5 paid orders created after 2026-10-01 without an intent', count(*)::text from marketplace_orders o where o.status='paid' and o.created_at > '2026-10-01' and not exists (select 1 from marketplace_payment_intents i where i.order_id=o.id)
  union all select 25, 'M5 duplicate txnid / payu_txn_id / provider ref', (select count(*) from (select txnid from marketplace_orders where txnid is not null group by 1 having count(*)>1) a)::text || ' / ' || (select count(*) from (select payu_txn_id from marketplace_orders where payu_txn_id is not null group by 1 having count(*)>1) b)::text || ' / ' || (select count(*) from (select provider, provider_intent_id from marketplace_payment_intents where provider_intent_id is not null group by 1,2 having count(*)>1) c)::text
  union all select 26, 'M4 orders whose lines are in another currency (historical)', count(*)::text from marketplace_orders o where exists (select 1 from marketplace_order_items i where i.order_id=o.id and i.currency <> o.currency)
  -- Refunds, licences, commissions
  union all select 30, 'H6 orders with processed refunds covering the total but not refunded', count(*)::text from marketplace_orders o where o.status <> 'refunded' and (select coalesce(sum(amount),0) from marketplace_order_refunds r where r.order_id=o.id and r.status='processed') >= o.total and o.total > 0
  union all select 31, 'H6 refund settlement triggers installed', (select count(*)::text from pg_trigger where tgrelid='marketplace_order_refunds'::regclass and tgname in ('marketplace_refund_settle','marketplace_refund_stamp') and tgenabled='O')
  union all select 32, 'M3 licences per order > 1', count(*)::text from (select order_id from licenses group by 1 having count(*)>1) x
  union all select 33, 'H7 commissions on orders that are not paid', ((select count(*) from marketplace_commissions c join marketplace_order_items i on i.id=c.order_item_id join marketplace_orders o on o.id=i.order_id where o.status not in ('paid','processing','fulfilled','completed','refunded') and c.status <> 'reversed') + (select count(*) from reseller_commissions c join marketplace_orders o on o.id=c.order_id where o.status not in ('paid','processing','fulfilled','completed','refunded') and c.status <> 'reversed') + (select count(*) from partner_commissions c join marketplace_orders o on o.id=c.order_id where o.status not in ('paid','processing','fulfilled','completed','refunded') and c.status <> 'reversed'))::text
  union all select 34, 'H7 self-purchase author commissions not reversed (historical)', count(*)::text from marketplace_commissions c join marketplace_order_items i on i.id=c.order_item_id join marketplace_orders o on o.id=i.order_id join marketplace_sellers s on s.id=c.seller_id where s.owner_user_id = coalesce(o.user_id,o.buyer_id) and c.status <> 'reversed'
  union all select 35, 'H7 seller release refuses unpaid/self-purchase', (select (position('owner_user_id is distinct from' in prosrc) > 0)::text from pg_proc where proname='mm_seller_earnings_release')
  union all select 36, 'M2 invoices per order > 1', count(*)::text from (select line_items->'meta'->>'order_id' from finance_invoices where doc_type='invoice' and line_items->'meta'->>'order_id' is not null group by 1 having count(*)>1) x
  -- History, notifications, sellers
  union all select 40, 'H8/H9 cascades remaining on the 23 history keys', count(*)::text from pg_constraint where contype='f' and confdeltype='c' and conname in ('marketplace_order_items_order_id_fkey','marketplace_order_status_history_order_id_fkey','marketplace_order_attributions_order_id_fkey','licenses_order_id_fkey','payment_logs_order_id_fkey','entitlements_product_id_fkey','finance_wallet_transactions_wallet_id_fkey','wallet_transactions_wallet_id_fkey','finance_invoice_items_invoice_id_fkey','payment_blacklist_user_id_fkey','sales_commissions_member_id_fkey','reseller_membership_orders_reseller_id_fkey','reseller_membership_entitlements_membership_id_fkey','author_approval_history_submission_id_fkey','trust_audit_logs_badge_key_fkey','ams_award_ledger_user_id_fkey','ams_activity_events_user_id_fkey','ams_certificates_user_id_fkey','ams_passports_user_id_fkey','user_awards_user_id_fkey','user_awards_award_id_fkey','xp_transactions_user_id_fkey','claims_user_id_fkey')
  union all select 41, 'H10 notifications owned by no user (historical test run)', count(*)::text from user_notifications n where not exists (select 1 from auth.users u where u.id=n.user_id)
  union all select 42, 'H10 owner key present', (select count(*)::text from pg_constraint where conname='user_notifications_user_id_fkey')
  union all select 43, 'H11 order lines without seller whose product has one', count(*)::text from marketplace_order_items i join marketplace_products p on p.id=i.product_id where i.seller_id is null and p.seller_id is not null
  union all select 44, 'H11 order lines for platform-owned products (seller NULL by design)', count(*)::text from marketplace_order_items where seller_id is null
  -- AMS
  union all select 50, 'AMS ledger lines / events / claimed duplicates', (select count(*) from ams_award_ledger)::text || ' / ' || (select count(*) from ams_activity_events)::text || ' / ' || (select count(*) from (select user_id, asset_kind, asset_slug from ams_award_ledger where reason='claimed' group by 1,2,3 having count(*)>1) x)::text
  union all select 51, 'M15 leaderboard has a key to profiles', (select count(*)::text from pg_constraint c where c.conrelid='leaderboard_entries'::regclass and c.contype='f' and c.confrelid='profiles'::regclass)
  -- Duplicates and drift
  union all select 60, 'duplicate business keys (emails, order numbers, licence keys, referral codes)', ((select count(*) from (select lower(email) from auth.users where email is not null group by 1 having count(*)>1) a) + (select count(*) from (select order_number from marketplace_orders group by 1 having count(*)>1) b) + (select count(*) from (select license_key from marketplace_licenses group by 1 having count(*)>1) c) + (select count(*) from (select code from marketplace_referral_codes group by 1 having count(*)>1) d))::text
  union all select 61, 'M13 recorded migration versions', (select count(*)::text from supabase_migrations.schema_migrations)
) x order by o;
