#!/bin/bash
# Regenerates /etc/nginx/conf.d/cloudflare-realip.conf from Cloudflare's
# published address lists, so nginx takes the visitor address from
# CF-Connecting-IP only when the connection really comes from Cloudflare.
# A request that reaches the origin directly keeps its own address, whatever
# headers it sends. Run weekly; nginx is reloaded only when the list changed
# and the configuration still tests clean.
set -euo pipefail
OUT=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)
v4=$(curl -fsS -m 30 https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS -m 30 https://www.cloudflare.com/ips-v6)
[ "$(printf '%s\n' "$v4" | grep -c /)" -ge 10 ] || { echo "unexpected v4 list"; exit 1; }
{
  echo "# Generated by /root/cf-realip-update.sh from cloudflare.com/ips-v4 and ips-v6 — do not edit."
  printf '%s\n%s\n' "$v4" "$v6" | grep / | sed 's/^/set_real_ip_from /; s/$/;/'
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive off;"
} > "$TMP"
if [ -f "$OUT" ] && cmp -s "$TMP" "$OUT"; then rm -f "$TMP"; echo "unchanged"; exit 0; fi
cp -f "$OUT" "$OUT.prev" 2>/dev/null || true
mv "$TMP" "$OUT"; chmod 644 "$OUT"
if nginx -t 2>/dev/null; then systemctl reload nginx; echo "updated and reloaded"; else
  [ -f "$OUT.prev" ] && mv "$OUT.prev" "$OUT" || rm -f "$OUT"; echo "nginx -t failed; previous list kept"; exit 1; fi
