-- Additive AI/API Manager registry expansion (batch 3)
-- Global expansion pass: AI (Meta Llama, xAI Grok, Google/Azure/AWS AI
-- services, video/image/voice generation, NLU), SEO intelligence
-- (Semrush, Ahrefs, SimilarWeb, SpyFu, GTmetrix, WebPageTest, Chrome UX
-- Report, W3C validator), social (Instagram Graph, YouTube Analytics,
-- Threads, Mastodon, Bluesky, VK, WeChat, LINE), analytics (Matomo,
-- Microsoft Clarity), business/local (Bing Places, Yelp Fusion),
-- marketing/CRM (Klaviyo, Zoho CRM), developer/cloud (AWS, Azure, GCP
-- general APIs, Datadog, Sentry, Netlify), and payments (Razorpay,
-- PayPal). All rows inserted as status='inactive' / approval_status=
-- 'pending' (catalogue-only; no credentials created, nothing
-- activated). Idempotent: safe to re-run.

INSERT INTO public.api_services (
  name, slug, type, category, status, endpoint_url, official_url, docs_url,
  auth_type, pricing_tier, owner_team, approval_status, terms_url,
  supported_countries, supported_search_engines, connected_modules, commercial_use_notes
) VALUES
  -- AI / LLM / agent ecosystems
  ('Meta Llama API', 'meta-llama-api', 'external', 'ai', 'inactive', 'https://api.llama.com/v1', 'https://llama.developer.meta.com', 'https://llama.developer.meta.com/docs/overview', 'api_key', 'free-tier', 'AI', 'pending', 'https://llama.developer.meta.com/legal/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Meta Llama API developer account and API key.'),
  ('xAI Grok API', 'xai-grok-api', 'external', 'ai', 'inactive', 'https://api.x.ai/v1', 'https://x.ai/api', 'https://docs.x.ai', 'api_key', 'paid', 'AI', 'pending', 'https://x.ai/legal/terms-of-service-enterprise', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an xAI developer account (paid, usage-billed) and API key.'),
  ('Google Cloud Natural Language API', 'google-cloud-natural-language-api', 'external', 'ai', 'inactive', 'https://language.googleapis.com/v1', 'https://cloud.google.com/natural-language', 'https://cloud.google.com/natural-language/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable the Natural Language API on a Google Cloud project with billing and OAuth/service-account credentials.'),
  ('Google Cloud Document AI', 'google-cloud-document-ai', 'external', 'ai', 'inactive', 'https://documentai.googleapis.com/v1', 'https://cloud.google.com/document-ai', 'https://cloud.google.com/document-ai/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable Document AI on a Google Cloud project with billing and a configured processor.'),
  ('Azure AI Vision', 'azure-computer-vision', 'external', 'ai', 'inactive', NULL, 'https://azure.microsoft.com/en-us/products/ai-services/ai-vision', 'https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/', 'api_key', 'free-tier', 'AI', 'pending', 'https://azure.microsoft.com/en-us/support/legal/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an Azure AI Vision resource (Azure subscription) and API key.'),
  ('Azure AI Speech', 'azure-ai-speech', 'external', 'ai', 'inactive', NULL, 'https://azure.microsoft.com/en-us/products/ai-services/ai-speech', 'https://learn.microsoft.com/en-us/azure/ai-services/speech-service/', 'api_key', 'free-tier', 'AI', 'pending', 'https://azure.microsoft.com/en-us/support/legal/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an Azure AI Speech resource (Azure subscription) and API key.'),
  ('Amazon Rekognition', 'aws-rekognition', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/rekognition/', 'https://docs.aws.amazon.com/rekognition/latest/APIReference/Welcome.html', 'iam', 'free-tier', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account with IAM credentials scoped to Rekognition.'),
  ('Amazon Transcribe', 'aws-transcribe', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/transcribe/', 'https://docs.aws.amazon.com/transcribe/latest/APIReference/Welcome.html', 'iam', 'paid', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account with IAM credentials scoped to Transcribe.'),
  ('Amazon Polly', 'aws-polly', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/polly/', 'https://docs.aws.amazon.com/polly/latest/dg/API_Reference.html', 'iam', 'free-tier', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account with IAM credentials scoped to Polly.'),
  ('Amazon Translate', 'aws-translate', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/translate/', 'https://docs.aws.amazon.com/translate/latest/APIReference/Welcome.html', 'iam', 'free-tier', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account with IAM credentials scoped to Translate.'),
  ('Amazon Comprehend', 'aws-comprehend', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/comprehend/', 'https://docs.aws.amazon.com/comprehend/latest/APIReference/Welcome.html', 'iam', 'free-tier', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account with IAM credentials scoped to Comprehend.'),
  ('Together AI API', 'together-ai-api', 'external', 'ai', 'inactive', 'https://api.together.xyz/v1', 'https://www.together.ai', 'https://docs.together.ai', 'api_key', 'free-tier', 'AI', 'pending', 'https://www.together.ai/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Together AI account and API key.'),
  ('Fireworks AI API', 'fireworks-ai-api', 'external', 'ai', 'inactive', 'https://api.fireworks.ai/inference/v1', 'https://fireworks.ai', 'https://docs.fireworks.ai', 'api_key', 'free-tier', 'AI', 'pending', 'https://fireworks.ai/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Fireworks AI account and API key.'),
  ('OpenRouter API', 'openrouter-api', 'external', 'ai', 'inactive', 'https://openrouter.ai/api/v1', 'https://openrouter.ai', 'https://openrouter.ai/docs', 'api_key', 'free-tier', 'AI', 'pending', 'https://openrouter.ai/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an OpenRouter account and API key; some routed models are free, most are usage-billed.'),
  ('Runway API', 'runway-api', 'external', 'ai', 'inactive', 'https://api.dev.runwayml.com', 'https://runwayml.com', 'https://docs.dev.runwayml.com', 'api_key', 'paid', 'AI', 'pending', 'https://runwayml.com/terms-of-use', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Runway Developer account (paid, usage-billed) and API key. Video generation capability.'),
  ('Luma AI API', 'luma-ai-api', 'external', 'ai', 'inactive', 'https://api.lumalabs.ai', 'https://lumalabs.ai', 'https://docs.lumalabs.ai', 'api_key', 'paid', 'AI', 'pending', 'https://lumalabs.ai/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Luma AI Dream Machine API account (paid, usage-billed) and API key. Video generation capability.'),
  ('Ideogram API', 'ideogram-api', 'external', 'ai', 'inactive', 'https://api.ideogram.ai', 'https://ideogram.ai', 'https://developer.ideogram.ai', 'api_key', 'paid', 'AI', 'pending', 'https://ideogram.ai/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an Ideogram developer account (paid, usage-billed) and API key. Image generation capability.'),
  ('PlayHT API', 'playht-api', 'external', 'ai', 'inactive', 'https://api.play.ht/api/v2', 'https://play.ht', 'https://docs.play.ht', 'api_key', 'free-tier', 'AI', 'pending', 'https://play.ht/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a PlayHT account and API key/user ID.'),
  ('Rev AI API', 'rev-ai-api', 'external', 'ai', 'inactive', 'https://api.rev.ai/speechtotext/v1', 'https://www.rev.ai', 'https://docs.rev.ai', 'token', 'free-tier', 'AI', 'pending', 'https://www.rev.ai/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Rev AI account and access token.'),
  ('Wit.ai API', 'wit-ai-api', 'external', 'ai', 'inactive', 'https://api.wit.ai', 'https://wit.ai', 'https://wit.ai/docs', 'token', 'free', 'AI', 'pending', 'https://www.facebook.com/legal/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Meta/Wit.ai app and server access token. Free natural-language-understanding capability.'),
  -- SEO / rank / competitor / technical intelligence
  ('Semrush API', 'semrush-api', 'external', 'seo-search', 'inactive', 'https://api.semrush.com', 'https://www.semrush.com', 'https://developer.semrush.com/api/', 'api_key', 'paid', 'SEO', 'pending', 'https://www.semrush.com/company/legal/api-tos/', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a Semrush account with an API-enabled plan (paid, unit-based billing) and API key. Keyword, rank-tracking, and competitor-intelligence capability.'),
  ('Ahrefs API', 'ahrefs-api', 'external', 'seo-search', 'inactive', 'https://api.ahrefs.com/v3', 'https://ahrefs.com', 'https://ahrefs.com/api/documentation', 'token', 'paid', 'SEO', 'pending', 'https://ahrefs.com/terms', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create an Ahrefs account with API access (paid, credit-metered) and API token. Backlink and domain-intelligence capability.'),
  ('SimilarWeb API', 'similarweb-api', 'external', 'seo-search', 'inactive', 'https://api.similarweb.com', 'https://www.similarweb.com', 'https://developers.similarweb.com', 'api_key', 'paid', 'SEO', 'pending', 'https://www.similarweb.com/corp/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a SimilarWeb API account (paid) and API key. Competitor/traffic-intelligence capability.'),
  ('SpyFu API', 'spyfu-api', 'external', 'seo-search', 'inactive', 'https://www.spyfu.com/apis', 'https://www.spyfu.com', 'https://www.spyfu.com/api', 'api_key', 'paid', 'SEO', 'pending', 'https://www.spyfu.com/terms', ARRAY['us','global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a SpyFu API account (paid) and API key. Competitor keyword-intelligence capability.'),
  ('GTmetrix API', 'gtmetrix-api', 'external', 'seo-performance', 'inactive', 'https://gtmetrix.com/api/2.0', 'https://gtmetrix.com', 'https://gtmetrix.com/api/', 'api_key', 'free-tier', 'SEO', 'pending', 'https://gtmetrix.com/terms-of-service.html', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a GTmetrix account and API key. Page-speed/performance auditing capability.'),
  ('WebPageTest API', 'webpagetest-api', 'external', 'seo-performance', 'inactive', 'https://www.webpagetest.org/api', 'https://www.webpagetest.org', 'https://docs.webpagetest.org/api/', 'api_key', 'free', 'SEO', 'pending', 'https://www.webpagetest.org/terms.php', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: request a free WebPageTest API key. Performance/Core Web Vitals lab-data capability.'),
  ('Chrome UX Report API', 'chrome-ux-report-api', 'external', 'seo-performance', 'inactive', 'https://chromeuxreport.googleapis.com/v1', 'https://developer.chrome.com/docs/crux', 'https://developer.chrome.com/docs/crux/api', 'api_key', 'free', 'SEO', 'pending', 'https://developers.google.com/terms', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: enable the Chrome UX Report API and generate a Google Cloud API key. Real-world Core Web Vitals field-data capability, free within published quotas.'),
  ('W3C Markup Validator API', 'w3c-markup-validator-api', 'external', 'seo-technical', 'inactive', 'https://validator.w3.org/nu/', 'https://validator.w3.org', 'https://validator.w3.org/docs/api.html', 'none', 'free', 'SEO', 'pending', 'https://www.w3.org/Consortium/Legal/ipr-notice', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'No authentication required. Free HTML/structured-markup validation capability, subject to W3C fair-use rate limits.'),
  -- Social
  ('Instagram Graph API', 'instagram-graph-api', 'external', 'seo-social', 'inactive', 'https://graph.facebook.com', 'https://developers.facebook.com/docs/instagram-api', 'https://developers.facebook.com/docs/instagram-api', 'oauth2', 'free', 'Growth', 'pending', 'https://developers.facebook.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: Meta Business verification, an Instagram Professional account linked to a Facebook Page, and app review for restricted permissions.'),
  ('YouTube Analytics API', 'youtube-analytics-api', 'external', 'seo-video', 'inactive', 'https://youtubeanalytics.googleapis.com/v2', 'https://developers.google.com/youtube/analytics', 'https://developers.google.com/youtube/analytics/reference', 'oauth2', 'free', 'SEO', 'pending', 'https://developers.google.com/youtube/terms/api-services-terms-of-service', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: OAuth-authorized YouTube channel owner/manager account.'),
  ('Threads API', 'threads-api', 'external', 'seo-social', 'inactive', 'https://graph.threads.net', 'https://developers.facebook.com/docs/threads', 'https://developers.facebook.com/docs/threads', 'oauth2', 'free', 'Growth', 'pending', 'https://developers.facebook.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: Meta developer app with Threads API product added and OAuth consent from the Threads account owner.'),
  ('Mastodon API', 'mastodon-api', 'external', 'seo-social', 'inactive', NULL, 'https://joinmastodon.org', 'https://docs.joinmastodon.org/api/', 'oauth2', 'free', 'Growth', 'pending', 'https://joinmastodon.org/tos', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'Open-protocol API; endpoint depends on the chosen Mastodon instance. ACTION REQUIRED: register an OAuth application on the target instance.'),
  ('Bluesky AT Protocol API', 'bluesky-at-protocol', 'external', 'seo-social', 'inactive', 'https://bsky.social/xrpc', 'https://bsky.app', 'https://docs.bsky.app', 'app_password', 'free', 'Growth', 'pending', 'https://bsky.social/about/support/tos', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Bluesky account and an app password (or OAuth client) for API access. Free, open protocol.'),
  ('VK API', 'vk-api', 'external', 'seo-social', 'inactive', 'https://api.vk.com/method', 'https://vk.com', 'https://dev.vk.com/en/reference', 'oauth2', 'free', 'Growth', 'pending', 'https://vk.com/terms', ARRAY['russia','cis']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: register a VK application and complete OAuth authorization. Regional (Russia/CIS) social platform.'),
  ('WeChat Official Account API', 'wechat-official-account-api', 'external', 'seo-social', 'inactive', 'https://api.weixin.qq.com', 'https://www.wechat.com', 'https://developers.weixin.qq.com/doc/offiaccount/en/Getting_Started/Overview.html', 'app_id_secret', 'free', 'Growth', 'pending', 'https://www.wechat.com/en/service_agreement.html', ARRAY['china']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: register a WeChat Official Account (business verification typically required) and obtain AppID/AppSecret. Regional (China) platform.'),
  ('LINE Messaging API', 'line-messaging-api', 'external', 'seo-social', 'inactive', 'https://api.line.me', 'https://developers.line.biz', 'https://developers.line.biz/en/docs/messaging-api/overview/', 'token', 'free-tier', 'Growth', 'pending', 'https://terms2.line.me/LINE_Developers_Agreement', ARRAY['japan','thailand','taiwan']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a LINE Official Account and Messaging API channel access token. Regional (Japan/Thailand/Taiwan) platform.'),
  -- Analytics
  ('Matomo Reporting API', 'matomo-api', 'external', 'seo-analytics', 'inactive', NULL, 'https://matomo.org', 'https://developer.matomo.org/api-reference/reporting-api', 'token', 'free', 'SEO', 'pending', 'https://matomo.org/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: self-hosted or Matomo Cloud instance with an API auth token. Open-source, privacy-focused analytics.'),
  ('Microsoft Clarity Data Export API', 'microsoft-clarity-api', 'external', 'seo-analytics', 'inactive', 'https://www.clarity.ms/export-data/api/v1', 'https://clarity.microsoft.com', 'https://learn.microsoft.com/en-us/clarity/data-export/data-export-api', 'api_key', 'free', 'SEO', 'pending', 'https://www.microsoft.com/en-us/servicesagreement', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a Microsoft Clarity project and generate an API token. Free heatmap/session-analytics capability.'),
  -- Business / local
  ('Bing Places for Business', 'bing-places-for-business', 'external', 'business-local', 'inactive', NULL, 'https://www.bingplaces.com', 'https://www.bing.com/webmasters/help/bing-places-for-business-9d7972b9', 'oauth2', 'free', 'SEO', 'pending', 'https://www.microsoft.com/en-us/servicesagreement', ARRAY['global']::text[], ARRAY['Bing']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: verify business listing ownership via Bing Places; primarily a managed portal with limited bulk/API tooling.'),
  ('Yelp Fusion API', 'yelp-fusion-api', 'external', 'business-local', 'inactive', 'https://api.yelp.com/v3', 'https://www.yelp.com/developers', 'https://docs.developer.yelp.com', 'api_key', 'free-tier', 'SEO', 'pending', 'https://www.yelp.com/developers/api_terms', ARRAY['us','canada']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a Yelp developer account and API key. Business listing/review-intelligence capability (US/Canada coverage).'),
  -- Marketing / CRM
  ('Klaviyo API', 'klaviyo-api', 'external', 'developer', 'inactive', 'https://a.klaviyo.com/api', 'https://www.klaviyo.com', 'https://developers.klaviyo.com/en/reference/api_overview', 'api_key', 'free-tier', 'Growth', 'pending', 'https://www.klaviyo.com/legal/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Klaviyo account and private API key. Email/SMS marketing automation capability.'),
  ('Zoho CRM API', 'zoho-crm-api', 'external', 'developer', 'inactive', 'https://www.zohoapis.com/crm/v6', 'https://www.zoho.com/crm', 'https://www.zoho.com/crm/developer/docs/api/v6/', 'oauth2', 'free-tier', 'Growth', 'pending', 'https://www.zoho.com/terms.html', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Zoho CRM account and OAuth client (self-client or server-based).'),
  -- Developer / Cloud (general provider surfaces)
  ('Amazon Web Services API', 'amazon-web-services-api', 'external', 'developer', 'inactive', NULL, 'https://aws.amazon.com', 'https://docs.aws.amazon.com', 'iam', 'paid', 'Platform', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AWS account and scoped IAM credentials. General entry covering AWS services beyond individually catalogued ones (Rekognition, Transcribe, Polly, Translate, Comprehend, Bedrock).'),
  ('Microsoft Azure API', 'microsoft-azure-api', 'external', 'developer', 'inactive', NULL, 'https://azure.microsoft.com', 'https://learn.microsoft.com/en-us/rest/api/azure/', 'oauth2', 'paid', 'Platform', 'pending', 'https://azure.microsoft.com/en-us/support/legal/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an Azure subscription and app registration (service principal). General entry covering Azure services beyond individually catalogued ones (OpenAI, AI Vision, AI Speech).'),
  ('Google Cloud Platform API', 'google-cloud-platform-api', 'external', 'developer', 'inactive', NULL, 'https://cloud.google.com', 'https://cloud.google.com/apis/docs/overview', 'oauth2', 'free-tier', 'Platform', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Google Cloud project with billing and a service account. General entry covering GCP services beyond individually catalogued ones (Vision, Translation, Speech, Natural Language, Document AI, Maps).'),
  ('Datadog API', 'datadog-api', 'external', 'developer', 'inactive', 'https://api.datadoghq.com/api/v2', 'https://www.datadoghq.com', 'https://docs.datadoghq.com/api/latest/', 'api_key', 'free-tier', 'Platform', 'pending', 'https://www.datadoghq.com/legal/terms-of-service/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Datadog account and API/application key. Monitoring/observability capability.'),
  ('Sentry API', 'sentry-api', 'external', 'developer', 'inactive', 'https://sentry.io/api/0', 'https://sentry.io', 'https://docs.sentry.io/api/', 'token', 'free-tier', 'Platform', 'pending', 'https://sentry.io/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Sentry account and auth token. Error-tracking/logging capability.'),
  ('Netlify API', 'netlify-api', 'external', 'developer', 'inactive', 'https://api.netlify.com/api/v1', 'https://www.netlify.com', 'https://docs.netlify.com/api/get-started/', 'token', 'free-tier', 'Platform', 'pending', 'https://www.netlify.com/legal/terms-of-use/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Netlify account and personal access token. Deployment capability.'),
  -- Payments
  ('Razorpay API', 'razorpay-api', 'external', 'payments', 'inactive', 'https://api.razorpay.com/v1', 'https://razorpay.com', 'https://razorpay.com/docs/api/', 'api_key', 'paid', 'Finance', 'pending', 'https://razorpay.com/terms/', ARRAY['india']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: complete Razorpay business KYC/verification and generate API key/secret. India-focused; supports UPI, cards, netbanking.'),
  ('PayPal API', 'paypal-api', 'external', 'payments', 'inactive', 'https://api-m.paypal.com', 'https://www.paypal.com', 'https://developer.paypal.com/api/rest/', 'oauth2', 'free-tier', 'Finance', 'pending', 'https://www.paypal.com/us/legalhub/useragreement-full', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a PayPal Developer/Business account and REST API app credentials (client ID/secret). Transaction fees apply on live payments.')
ON CONFLICT (slug) DO NOTHING;

-- Capability records for the new services above (catalogued only;
-- automation_status remains manual_test_required until an owner-approved
-- real test is executed in the separate verification/activation phase).
INSERT INTO public.api_service_capabilities (
  service_id, capability_key, capability_name, official_docs_url,
  api_available, pricing_tier, authentication_type, supported_search_engines,
  automation_status, verification_status, approval_status
)
SELECT s.id, c.capability_key, c.capability_name, c.docs_url,
       c.api_available, c.pricing_tier, c.auth_type, c.engines,
       'manual_test_required', 'catalogued', 'pending'
FROM public.api_services s
JOIN (
  VALUES
    ('meta-llama-api','text_generation','Llama model text generation','https://llama.developer.meta.com/docs/overview',true,'free-tier','api_key',ARRAY[]::text[]),
    ('xai-grok-api','text_generation','Grok model text generation','https://docs.x.ai',true,'paid','api_key',ARRAY[]::text[]),
    ('google-cloud-natural-language-api','sentiment_analysis','Entity and sentiment analysis','https://cloud.google.com/natural-language/docs/reference/rest',true,'free-tier','oauth2',ARRAY[]::text[]),
    ('google-cloud-document-ai','ocr','Document OCR and structured extraction','https://cloud.google.com/document-ai/docs/reference/rest',true,'free-tier','oauth2',ARRAY[]::text[]),
    ('azure-computer-vision','ocr','Image OCR and visual analysis','https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/overview-ocr',true,'free-tier','api_key',ARRAY[]::text[]),
    ('azure-ai-speech','speech_to_text','Speech recognition','https://learn.microsoft.com/en-us/azure/ai-services/speech-service/speech-to-text',true,'free-tier','api_key',ARRAY[]::text[]),
    ('azure-ai-speech','text_to_speech','Neural voice synthesis','https://learn.microsoft.com/en-us/azure/ai-services/speech-service/text-to-speech',true,'free-tier','api_key',ARRAY[]::text[]),
    ('aws-rekognition','vision','Image and video content analysis','https://docs.aws.amazon.com/rekognition/latest/dg/what-is.html',true,'free-tier','iam',ARRAY[]::text[]),
    ('aws-transcribe','speech_to_text','Automatic speech recognition','https://docs.aws.amazon.com/transcribe/latest/dg/what-is-transcribe.html',true,'paid','iam',ARRAY[]::text[]),
    ('aws-polly','text_to_speech','Text-to-speech synthesis','https://docs.aws.amazon.com/polly/latest/dg/what-is.html',true,'free-tier','iam',ARRAY[]::text[]),
    ('aws-translate','translation','Neural machine translation','https://docs.aws.amazon.com/translate/latest/dg/what-is.html',true,'free-tier','iam',ARRAY[]::text[]),
    ('aws-comprehend','nlp','Sentiment, entity and key-phrase extraction','https://docs.aws.amazon.com/comprehend/latest/dg/what-is.html',true,'free-tier','iam',ARRAY[]::text[]),
    ('together-ai-api','text_generation','Open-model hosted inference','https://docs.together.ai',true,'free-tier','api_key',ARRAY[]::text[]),
    ('fireworks-ai-api','text_generation','Open-model hosted inference','https://docs.fireworks.ai',true,'free-tier','api_key',ARRAY[]::text[]),
    ('openrouter-api','text_generation','Multi-provider model routing','https://openrouter.ai/docs',true,'free-tier','api_key',ARRAY[]::text[]),
    ('runway-api','video_generation','Text/image-to-video generation','https://docs.dev.runwayml.com',true,'paid','api_key',ARRAY[]::text[]),
    ('luma-ai-api','video_generation','Dream Machine video generation','https://docs.lumalabs.ai',true,'paid','api_key',ARRAY[]::text[]),
    ('ideogram-api','image_generation','Text-to-image generation','https://developer.ideogram.ai',true,'paid','api_key',ARRAY[]::text[]),
    ('playht-api','text_to_speech','Voice cloning and synthesis','https://docs.play.ht',true,'free-tier','api_key',ARRAY[]::text[]),
    ('rev-ai-api','speech_to_text','Speech-to-text transcription','https://docs.rev.ai',true,'free-tier','token',ARRAY[]::text[]),
    ('wit-ai-api','nlu','Intent and entity extraction','https://wit.ai/docs',true,'free','token',ARRAY[]::text[]),
    ('semrush-api','keyword_data','Keyword and rank-tracking data','https://developer.semrush.com/api/v3/analytics/',true,'paid','api_key',ARRAY['Google']::text[]),
    ('semrush-api','competitor_intelligence','Competitor domain analysis','https://developer.semrush.com/api/',true,'paid','api_key',ARRAY[]::text[]),
    ('ahrefs-api','backlinks','Backlink and referring-domain data','https://ahrefs.com/api/documentation/site-explorer',true,'paid','token',ARRAY[]::text[]),
    ('ahrefs-api','domain_intelligence','Domain rating and organic traffic estimates','https://ahrefs.com/api/documentation',true,'paid','token',ARRAY[]::text[]),
    ('similarweb-api','competitor_intelligence','Traffic and engagement estimates','https://developers.similarweb.com',true,'paid','api_key',ARRAY[]::text[]),
    ('spyfu-api','competitor_intelligence','Competitor keyword and ad intelligence','https://www.spyfu.com/api',true,'paid','api_key',ARRAY['Google']::text[]),
    ('gtmetrix-api','performance_audit','Page-speed performance audit','https://gtmetrix.com/api/',true,'free-tier','api_key',ARRAY[]::text[]),
    ('webpagetest-api','performance_audit','Lab-based Core Web Vitals testing','https://docs.webpagetest.org/api/',true,'free','api_key',ARRAY[]::text[]),
    ('chrome-ux-report-api','core_web_vitals','Field-data Core Web Vitals','https://developer.chrome.com/docs/crux/api',true,'free','api_key',ARRAY['Google']::text[]),
    ('w3c-markup-validator-api','structured_data','HTML/markup validation','https://validator.w3.org/docs/api.html',true,'free','none',ARRAY[]::text[]),
    ('instagram-graph-api','social_publishing','Business account content publishing and insights','https://developers.facebook.com/docs/instagram-api',true,'free','oauth2',ARRAY[]::text[]),
    ('youtube-analytics-api','video_analytics','Channel and video performance reporting','https://developers.google.com/youtube/analytics/reference',true,'free','oauth2',ARRAY['Google']::text[]),
    ('threads-api','social_publishing','Threads post publishing and insights','https://developers.facebook.com/docs/threads',true,'free','oauth2',ARRAY[]::text[]),
    ('mastodon-api','social_publishing','Federated timeline posting','https://docs.joinmastodon.org/api/',true,'free','oauth2',ARRAY[]::text[]),
    ('bluesky-at-protocol','social_publishing','AT Protocol post publishing','https://docs.bsky.app',true,'free','app_password',ARRAY[]::text[]),
    ('vk-api','social_publishing','Regional (Russia/CIS) social publishing','https://dev.vk.com/en/reference',true,'free','oauth2',ARRAY[]::text[]),
    ('wechat-official-account-api','social_publishing','Regional (China) official account messaging','https://developers.weixin.qq.com/doc/offiaccount/en/Getting_Started/Overview.html',true,'free','app_id_secret',ARRAY[]::text[]),
    ('line-messaging-api','social_publishing','Regional (Japan/Thailand/Taiwan) messaging','https://developers.line.biz/en/docs/messaging-api/overview/',true,'free-tier','token',ARRAY[]::text[]),
    ('matomo-api','web_analytics','Privacy-focused traffic analytics','https://developer.matomo.org/api-reference/reporting-api',true,'free','token',ARRAY[]::text[]),
    ('microsoft-clarity-api','session_analytics','Heatmap and session-replay data export','https://learn.microsoft.com/en-us/clarity/data-export/data-export-api',true,'free','api_key',ARRAY[]::text[]),
    ('bing-places-for-business','business_listing','Local business listing management','https://www.bing.com/webmasters/help/bing-places-for-business-9d7972b9',true,'free','oauth2',ARRAY['Bing']::text[]),
    ('yelp-fusion-api','business_reviews','Business listing and review data','https://docs.developer.yelp.com',true,'free-tier','api_key',ARRAY[]::text[]),
    ('klaviyo-api','email_marketing','Email/SMS campaign automation','https://developers.klaviyo.com/en/reference/api_overview',true,'free-tier','api_key',ARRAY[]::text[]),
    ('zoho-crm-api','crm','CRM record and pipeline management','https://www.zoho.com/crm/developer/docs/api/v6/',true,'free-tier','oauth2',ARRAY[]::text[]),
    ('datadog-api','monitoring','Infrastructure and application monitoring','https://docs.datadoghq.com/api/latest/',true,'free-tier','api_key',ARRAY[]::text[]),
    ('sentry-api','error_tracking','Application error and performance tracking','https://docs.sentry.io/api/',true,'free-tier','token',ARRAY[]::text[]),
    ('netlify-api','deployment','Static site/edge deployment management','https://docs.netlify.com/api/get-started/',true,'free-tier','token',ARRAY[]::text[]),
    ('razorpay-api','payment_processing','Payment order and settlement processing','https://razorpay.com/docs/api/',true,'paid','api_key',ARRAY[]::text[]),
    ('paypal-api','payment_processing','Payment order and settlement processing','https://developer.paypal.com/api/rest/',true,'free-tier','oauth2',ARRAY[]::text[])
) AS c(slug, capability_key, capability_name, docs_url, api_available, pricing_tier, auth_type, engines)
  ON s.slug = c.slug
ON CONFLICT (service_id, capability_key) DO NOTHING;
