-- Additive AI/API Manager registry expansion
-- Adds 36 new AI, vision, voice, translation, search/SEO, social, developer,
-- and permitted payment-rail (Wise, Binance) services plus their documented
-- capabilities to the central registry. All rows are inserted as
-- status='inactive' / approval_status='pending' (catalogue-only; no
-- credentials created, nothing activated). Idempotent: safe to re-run.

INSERT INTO public.api_services (
  name, slug, type, category, status, endpoint_url, official_url, docs_url,
  auth_type, pricing_tier, owner_team, approval_status, terms_url,
  supported_countries, supported_search_engines, connected_modules, commercial_use_notes
) VALUES
  ('Google Gemini API', 'google-gemini-api', 'external', 'ai', 'inactive', 'https://generativelanguage.googleapis.com/v1beta', 'https://ai.google.dev', 'https://ai.google.dev/gemini-api/docs', 'api_key', 'free-tier', 'AI', 'pending', 'https://ai.google.dev/gemini-api/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Google AI Studio API key (or Vertex AI service account) and store it as an encrypted credential.'),
  ('Azure OpenAI Service', 'azure-openai-service', 'external', 'ai', 'inactive', NULL, 'https://azure.microsoft.com/en-us/products/ai-services/openai-service', 'https://learn.microsoft.com/en-us/azure/ai-services/openai/reference', 'api_key', 'paid', 'AI', 'pending', 'https://azure.microsoft.com/en-us/support/legal/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: requires an Azure subscription, resource deployment, and approved model access before a key can be issued.'),
  ('Amazon Bedrock', 'amazon-bedrock', 'external', 'ai', 'inactive', NULL, 'https://aws.amazon.com/bedrock/', 'https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html', 'api_key', 'paid', 'AI', 'pending', 'https://aws.amazon.com/service-terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: requires an AWS account, IAM credentials with Bedrock access, and model access requests per provider.'),
  ('Cohere API', 'cohere-api', 'external', 'ai', 'inactive', 'https://api.cohere.com/v2', 'https://cohere.com', 'https://docs.cohere.com/reference/about', 'api_key', 'free-tier', 'AI', 'pending', 'https://cohere.com/terms-of-use', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Cohere account and API key.'),
  ('Mistral AI API', 'mistral-ai-api', 'external', 'ai', 'inactive', 'https://api.mistral.ai/v1', 'https://mistral.ai', 'https://docs.mistral.ai/api/', 'api_key', 'free-tier', 'AI', 'pending', 'https://mistral.ai/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a la Plateforme account and API key.'),
  ('Groq API', 'groq-api', 'external', 'ai', 'inactive', 'https://api.groq.com/openai/v1', 'https://groq.com', 'https://console.groq.com/docs/quickstart', 'api_key', 'free-tier', 'AI', 'pending', 'https://groq.com/terms-of-use/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a GroqCloud account and API key.'),
  ('Perplexity API', 'perplexity-api', 'external', 'ai', 'inactive', 'https://api.perplexity.ai', 'https://www.perplexity.ai', 'https://docs.perplexity.ai', 'api_key', 'paid', 'AI', 'pending', 'https://www.perplexity.ai/hub/legal/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Perplexity API account (paid) and API key.'),
  ('Hugging Face Inference API', 'huggingface-inference-api', 'external', 'ai', 'inactive', 'https://api-inference.huggingface.co', 'https://huggingface.co', 'https://huggingface.co/docs/api-inference/index', 'token', 'free-tier', 'AI', 'pending', 'https://huggingface.co/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Hugging Face account and access token; some models require accepting a gated-model license.'),
  ('Replicate API', 'replicate-api', 'external', 'ai', 'inactive', 'https://api.replicate.com/v1', 'https://replicate.com', 'https://replicate.com/docs/reference/http-api', 'token', 'paid', 'AI', 'pending', 'https://replicate.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Replicate account (paid, usage-billed) and API token.'),
  ('Stability AI API', 'stability-ai-api', 'external', 'ai', 'inactive', 'https://api.stability.ai', 'https://platform.stability.ai', 'https://platform.stability.ai/docs/api-reference', 'api_key', 'paid', 'AI', 'pending', 'https://platform.stability.ai/legal/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Stability AI Platform account and purchase API credits.'),
  ('AI21 Labs API', 'ai21-labs-api', 'external', 'ai', 'inactive', 'https://api.ai21.com/studio/v1', 'https://www.ai21.com', 'https://docs.ai21.com', 'api_key', 'free-tier', 'AI', 'pending', 'https://www.ai21.com/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AI21 Studio account and API key.'),
  ('DeepSeek API', 'deepseek-api', 'external', 'ai', 'inactive', 'https://api.deepseek.com', 'https://www.deepseek.com', 'https://api-docs.deepseek.com', 'api_key', 'paid', 'AI', 'pending', 'https://cdn.deepseek.com/policies/en-US/deepseek-open-platform-terms-of-service.html', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a DeepSeek open-platform account (paid) and API key.'),
  ('Google Cloud Vision API', 'google-cloud-vision-api', 'external', 'ai', 'inactive', 'https://vision.googleapis.com/v1', 'https://cloud.google.com/vision', 'https://cloud.google.com/vision/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable the Vision API on a Google Cloud project with billing and OAuth/service-account credentials.'),
  ('ElevenLabs API', 'elevenlabs-api', 'external', 'ai', 'inactive', 'https://api.elevenlabs.io/v1', 'https://elevenlabs.io', 'https://elevenlabs.io/docs/api-reference/introduction', 'api_key', 'free-tier', 'AI', 'pending', 'https://elevenlabs.io/terms-of-use', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an ElevenLabs account and API key.'),
  ('Deepgram API', 'deepgram-api', 'external', 'ai', 'inactive', 'https://api.deepgram.com/v1', 'https://deepgram.com', 'https://developers.deepgram.com/reference/', 'api_key', 'free-tier', 'AI', 'pending', 'https://deepgram.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Deepgram account and API key.'),
  ('AssemblyAI API', 'assemblyai-api', 'external', 'ai', 'inactive', 'https://api.assemblyai.com/v2', 'https://www.assemblyai.com', 'https://www.assemblyai.com/docs/api-reference/overview', 'api_key', 'free-tier', 'AI', 'pending', 'https://www.assemblyai.com/legal/terms-of-service', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an AssemblyAI account and API key.'),
  ('Google Cloud Speech-to-Text', 'google-cloud-speech-to-text', 'external', 'ai', 'inactive', 'https://speech.googleapis.com/v1', 'https://cloud.google.com/speech-to-text', 'https://cloud.google.com/speech-to-text/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable the Speech-to-Text API on a Google Cloud project with billing and OAuth/service-account credentials.'),
  ('Google Cloud Text-to-Speech', 'google-cloud-text-to-speech', 'external', 'ai', 'inactive', 'https://texttospeech.googleapis.com/v1', 'https://cloud.google.com/text-to-speech', 'https://cloud.google.com/text-to-speech/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable the Text-to-Speech API on a Google Cloud project with billing and OAuth/service-account credentials.'),
  ('Vimeo API', 'vimeo-api', 'external', 'seo-video', 'inactive', 'https://api.vimeo.com', 'https://developer.vimeo.com', 'https://developer.vimeo.com/api/reference', 'oauth2', 'free-tier', 'SEO', 'pending', 'https://vimeo.com/terms', ARRAY['global']::text[], ARRAY['Vimeo']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: register a Vimeo developer app and complete OAuth authorization.'),
  ('DeepL API', 'deepl-api', 'external', 'ai', 'inactive', 'https://api-free.deepl.com/v2', 'https://www.deepl.com/pro-api', 'https://developers.deepl.com/docs', 'api_key', 'free-tier', 'AI', 'pending', 'https://www.deepl.com/en/pro-license', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a DeepL API account (Free or Pro) and API key.'),
  ('Google Cloud Translation API', 'google-cloud-translation-api', 'external', 'ai', 'inactive', 'https://translation.googleapis.com/language/translate/v2', 'https://cloud.google.com/translate', 'https://cloud.google.com/translate/docs/reference/rest', 'oauth2', 'free-tier', 'AI', 'pending', 'https://cloud.google.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: enable the Cloud Translation API on a Google Cloud project with billing and OAuth/service-account credentials.'),
  ('Microsoft Translator Text API', 'microsoft-translator-text-api', 'external', 'ai', 'inactive', 'https://api.cognitive.microsofttranslator.com', 'https://www.microsoft.com/en-us/translator/business/', 'https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-reference', 'api_key', 'free-tier', 'AI', 'pending', 'https://www.microsoft.com/en-us/servicesagreement', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create an Azure AI Translator resource and API key.'),
  ('Google Custom Search JSON API', 'google-custom-search-api', 'external', 'seo-search', 'inactive', 'https://www.googleapis.com/customsearch/v1', 'https://developers.google.com/custom-search/v1/overview', 'https://developers.google.com/custom-search/v1/overview', 'api_key', 'free-tier', 'SEO', 'pending', 'https://developers.google.com/custom-search/terms', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a Programmable Search Engine, enable Custom Search API, and generate an API key (100 free queries/day, then paid).'),
  ('SerpAPI', 'serpapi', 'external', 'seo-search', 'inactive', 'https://serpapi.com/search', 'https://serpapi.com', 'https://serpapi.com/search-api', 'api_key', 'free-tier', 'SEO', 'pending', 'https://serpapi.com/legal', ARRAY['global']::text[], ARRAY['Google','Bing','Yandex','Baidu']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create a SerpAPI account and API key (limited free trial searches, then paid plan).'),
  ('Google Tag Manager API', 'google-tag-manager-api', 'external', 'seo-analytics', 'inactive', 'https://tagmanager.googleapis.com/tagmanager/v2', 'https://tagmanager.google.com', 'https://developers.google.com/tag-platform/tag-manager/api/v2', 'oauth2', 'free', 'SEO', 'pending', 'https://policies.google.com/terms', ARRAY['global']::text[], ARRAY['Google']::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: authorized Google account with edit access to the target GTM container and OAuth consent.'),
  ('Plausible Analytics Stats API', 'plausible-analytics-api', 'external', 'seo-analytics', 'inactive', 'https://plausible.io/api/v2', 'https://plausible.io', 'https://plausible.io/docs/stats-api', 'api_key', 'paid', 'SEO', 'pending', 'https://plausible.io/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager','Global SEO Tools']::text[], 'ACTION REQUIRED: create/host a Plausible site (paid product) and generate a Stats API key.'),
  ('Discord API', 'discord-api', 'external', 'seo-social', 'inactive', 'https://discord.com/api/v10', 'https://discord.com/developers/docs/intro', 'https://discord.com/developers/docs/intro', 'token', 'free', 'Growth', 'pending', 'https://discord.com/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: register a Discord application, create a bot, and invite it to the target server.'),
  ('Telegram Bot API', 'telegram-bot-api', 'external', 'seo-social', 'inactive', 'https://api.telegram.org', 'https://core.telegram.org/bots', 'https://core.telegram.org/bots/api', 'token', 'free', 'Growth', 'pending', 'https://telegram.org/tos', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a bot via @BotFather to obtain a bot token.'),
  ('WhatsApp Business Platform Cloud API', 'whatsapp-cloud-api', 'external', 'seo-social', 'inactive', 'https://graph.facebook.com', 'https://business.whatsapp.com/products/business-platform', 'https://developers.facebook.com/docs/whatsapp/cloud-api', 'oauth2', 'paid', 'Growth', 'pending', 'https://www.whatsapp.com/legal/business-terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: Meta Business verification, a WhatsApp Business Account, phone number registration, and app review for restricted permissions.'),
  ('GitLab API', 'gitlab-api', 'external', 'developer', 'inactive', 'https://gitlab.com/api/v4', 'https://about.gitlab.com', 'https://docs.gitlab.com/ee/api/rest/', 'token', 'free-tier', 'Platform', 'pending', 'https://about.gitlab.com/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a GitLab personal/project access token with the required scopes.'),
  ('Cloudflare API', 'cloudflare-api', 'external', 'developer', 'inactive', 'https://api.cloudflare.com/client/v4', 'https://developers.cloudflare.com', 'https://developers.cloudflare.com/api/', 'token', 'free-tier', 'Platform', 'pending', 'https://www.cloudflare.com/terms/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a scoped Cloudflare API token for the target zone/account.'),
  ('Twilio API', 'twilio-api', 'external', 'developer', 'inactive', 'https://api.twilio.com/2010-04-01', 'https://www.twilio.com', 'https://www.twilio.com/docs/usage/api', 'api_key', 'paid', 'Growth', 'pending', 'https://www.twilio.com/legal/tos', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Twilio account, verify a sender number/WhatsApp sender, and obtain Account SID/Auth Token.'),
  ('SendGrid API', 'sendgrid-api', 'external', 'developer', 'inactive', 'https://api.sendgrid.com/v3', 'https://sendgrid.com', 'https://docs.sendgrid.com/api-reference', 'api_key', 'free-tier', 'Growth', 'pending', 'https://www.twilio.com/legal/tos', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Twilio SendGrid account, verify sender identity/domain, and generate an API key.'),
  ('Mailchimp Marketing API', 'mailchimp-marketing-api', 'external', 'developer', 'inactive', NULL, 'https://mailchimp.com', 'https://mailchimp.com/developer/marketing/api/', 'api_key', 'free-tier', 'Growth', 'pending', 'https://www.intuit.com/legal/terms/en-us/mailchimp/', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: create a Mailchimp account and generate an API key for the account''s datacenter.'),
  ('Wise Platform API', 'wise-platform-api', 'external', 'developer', 'inactive', NULL, 'https://wise.com/gb/business/api', 'https://docs.wise.com/api-docs', 'api_key', 'free', 'Finance', 'pending', 'https://wise.com/legal/terms-of-use', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: Wise Business account plus API token/OAuth partner approval; this is one of Software Vala''s permitted payment rails.'),
  ('Binance API', 'binance-api', 'external', 'developer', 'inactive', 'https://api.binance.com', 'https://www.binance.com', 'https://binance-docs.github.io/apidocs/spot/en/', 'api_key', 'free', 'Finance', 'pending', 'https://www.binance.com/en/terms', ARRAY['global']::text[], ARRAY[]::text[], ARRAY['AI API Manager']::text[], 'ACTION REQUIRED: Binance account with API key/secret and IP allowlisting; this is one of Software Vala''s permitted payment rails.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.api_service_capabilities (
  service_id, capability_key, capability_name, official_docs_url, api_available,
  pricing_tier, authentication_type, supported_countries, supported_languages,
  supported_search_engines, automation_status, verification_status, approval_status
)
SELECT s.id, c.capability_key, c.capability_name, c.docs_url, c.api_available,
       c.pricing_tier, c.auth_type, ARRAY['global']::text[], ARRAY[]::text[], ARRAY[]::text[],
       'manual_test_required', 'catalogued', 'pending'
FROM (
  VALUES
    ('google-gemini-api', 'text-generation', 'Text Generation (Gemini)', 'https://ai.google.dev/gemini-api/docs/text-generation', true, 'free-tier', 'api_key'),
    ('google-gemini-api', 'vision-understanding', 'Multimodal / Vision Understanding', 'https://ai.google.dev/gemini-api/docs/vision', true, 'free-tier', 'api_key'),
    ('google-gemini-api', 'function-calling', 'Function Calling', 'https://ai.google.dev/gemini-api/docs/function-calling', true, 'free-tier', 'api_key'),
    ('azure-openai-service', 'chat-completions', 'Chat Completions (Azure-hosted OpenAI models)', 'https://learn.microsoft.com/en-us/azure/ai-services/openai/reference', true, 'paid', 'api_key'),
    ('azure-openai-service', 'embeddings', 'Embeddings', 'https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#embeddings', true, 'paid', 'api_key'),
    ('amazon-bedrock', 'model-invocation', 'Foundation Model Invocation (multi-vendor)', 'https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html', true, 'paid', 'api_key'),
    ('cohere-api', 'text-generation', 'Chat/Generate', 'https://docs.cohere.com/reference/chat', true, 'free-tier', 'api_key'),
    ('cohere-api', 'embeddings', 'Embed', 'https://docs.cohere.com/reference/embed', true, 'free-tier', 'api_key'),
    ('cohere-api', 'rerank', 'Rerank', 'https://docs.cohere.com/reference/rerank', true, 'free-tier', 'api_key'),
    ('mistral-ai-api', 'chat-completions', 'Chat Completions', 'https://docs.mistral.ai/api/#tag/chat', true, 'free-tier', 'api_key'),
    ('mistral-ai-api', 'embeddings', 'Embeddings', 'https://docs.mistral.ai/api/#tag/embeddings', true, 'free-tier', 'api_key'),
    ('groq-api', 'chat-completions', 'Chat Completions (LPU inference)', 'https://console.groq.com/docs/api-reference#chat', true, 'free-tier', 'api_key'),
    ('perplexity-api', 'search-augmented-chat', 'Search-augmented Chat Completions', 'https://docs.perplexity.ai/api-reference/chat-completions', true, 'paid', 'api_key'),
    ('huggingface-inference-api', 'model-inference', 'Hosted Model Inference', 'https://huggingface.co/docs/api-inference/index', true, 'free-tier', 'token'),
    ('replicate-api', 'model-run', 'Run Public/Private Models', 'https://replicate.com/docs/reference/http-api#predictions.create', true, 'paid', 'token'),
    ('stability-ai-api', 'image-generation', 'Text-to-Image Generation', 'https://platform.stability.ai/docs/api-reference#tag/Generate', true, 'paid', 'api_key'),
    ('ai21-labs-api', 'text-generation', 'Chat/Completion', 'https://docs.ai21.com/reference/jamba-chat-completions-api', true, 'free-tier', 'api_key'),
    ('deepseek-api', 'chat-completions', 'Chat Completions', 'https://api-docs.deepseek.com/api/create-chat-completion', true, 'paid', 'api_key'),
    ('google-cloud-vision-api', 'label-detection', 'Label/Object Detection', 'https://cloud.google.com/vision/docs/labels', true, 'free-tier', 'oauth2'),
    ('google-cloud-vision-api', 'ocr', 'Text Detection / OCR', 'https://cloud.google.com/vision/docs/ocr', true, 'free-tier', 'oauth2'),
    ('elevenlabs-api', 'text-to-speech', 'Text-to-Speech', 'https://elevenlabs.io/docs/api-reference/text-to-speech', true, 'free-tier', 'api_key'),
    ('deepgram-api', 'speech-to-text', 'Speech-to-Text Transcription', 'https://developers.deepgram.com/reference/listen-remote', true, 'free-tier', 'api_key'),
    ('assemblyai-api', 'speech-to-text', 'Speech-to-Text Transcription', 'https://www.assemblyai.com/docs/api-reference/transcripts/submit', true, 'free-tier', 'api_key'),
    ('google-cloud-speech-to-text', 'speech-to-text', 'Speech Recognition', 'https://cloud.google.com/speech-to-text/docs/reference/rest', true, 'free-tier', 'oauth2'),
    ('google-cloud-text-to-speech', 'text-to-speech', 'Speech Synthesis', 'https://cloud.google.com/text-to-speech/docs/reference/rest', true, 'free-tier', 'oauth2'),
    ('vimeo-api', 'video-upload', 'Video Upload/Management', 'https://developer.vimeo.com/api/reference/videos', true, 'free-tier', 'oauth2'),
    ('deepl-api', 'translation', 'Text Translation', 'https://developers.deepl.com/docs/api-reference/translate', true, 'free-tier', 'api_key'),
    ('google-cloud-translation-api', 'translation', 'Text Translation', 'https://cloud.google.com/translate/docs/reference/rest/v2/translate', true, 'free-tier', 'oauth2'),
    ('microsoft-translator-text-api', 'translation', 'Text Translation', 'https://learn.microsoft.com/en-us/azure/ai-services/translator/reference/v3-0-translate', true, 'free-tier', 'api_key'),
    ('google-custom-search-api', 'web-search', 'Web Search Results (Google)', 'https://developers.google.com/custom-search/v1/using_rest', true, 'free-tier', 'api_key'),
    ('serpapi', 'serp-scraping', 'Search Engine Results (multi-engine)', 'https://serpapi.com/search-api', true, 'free-tier', 'api_key'),
    ('google-tag-manager-api', 'container-management', 'GTM Container/Tag Management', 'https://developers.google.com/tag-platform/tag-manager/api/v2/reference', true, 'free', 'oauth2'),
    ('plausible-analytics-api', 'analytics-query', 'Site Analytics Query', 'https://plausible.io/docs/stats-api', true, 'paid', 'api_key'),
    ('discord-api', 'bot-messaging', 'Bot Messaging/Webhooks', 'https://discord.com/developers/docs/resources/webhook', true, 'free', 'token'),
    ('telegram-bot-api', 'bot-messaging', 'Bot Messaging', 'https://core.telegram.org/bots/api#sendmessage', true, 'free', 'token'),
    ('whatsapp-cloud-api', 'business-messaging', 'Business Messaging', 'https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages', true, 'paid', 'oauth2'),
    ('gitlab-api', 'repo-management', 'Repository/Issue Management', 'https://docs.gitlab.com/ee/api/rest/', true, 'free-tier', 'token'),
    ('cloudflare-api', 'dns-management', 'DNS/Zone Management', 'https://developers.cloudflare.com/api/operations/zones-get', true, 'free-tier', 'token'),
    ('cloudflare-api', 'cache-purge', 'Cache Purge', 'https://developers.cloudflare.com/api/operations/zone-purge', true, 'free-tier', 'token'),
    ('twilio-api', 'sms-messaging', 'SMS/WhatsApp Messaging', 'https://www.twilio.com/docs/sms/api', true, 'paid', 'api_key'),
    ('sendgrid-api', 'transactional-email', 'Transactional Email Send', 'https://docs.sendgrid.com/api-reference/mail-send/mail-send', true, 'free-tier', 'api_key'),
    ('mailchimp-marketing-api', 'email-campaigns', 'Audience/Campaign Management', 'https://mailchimp.com/developer/marketing/api/campaigns/', true, 'free-tier', 'api_key'),
    ('wise-platform-api', 'payouts', 'Cross-border Transfers/Payouts', 'https://docs.wise.com/api-docs/api-reference/transfer', true, 'free', 'api_key'),
    ('binance-api', 'market-data', 'Public Market Data', 'https://binance-docs.github.io/apidocs/spot/en/#market-data-endpoints', true, 'free', 'none'),
    ('binance-api', 'wallet', 'Wallet/Deposit-Withdraw', 'https://binance-docs.github.io/apidocs/spot/en/#wallet-endpoints', true, 'free', 'api_key')
) AS c(slug, capability_key, capability_name, docs_url, api_available, pricing_tier, auth_type)
JOIN public.api_services s ON s.slug = c.slug
ON CONFLICT (service_id, capability_key) DO NOTHING;
