-- The sales workforce itself.
--
-- Seven regional agents for the markets this platform genuinely sells into,
-- and forty-seven specializations for the distinct pieces of sales work it
-- has records for: leads, follow-ups, demos, subscriptions, renewals,
-- resellers, franchises, marketplace orders.
--
-- The specializations are global rather than duplicated per region. Seven
-- copies of "Quotation Agent" would be a larger number and the same
-- workforce; the regional agents coordinate, the specialists do the work.
--
-- Every one of them holds READ, ANALYZE, RECOMMEND and CREATE, and not one
-- holds EXECUTE_LOW_RISK. They qualify, follow up, draft and recommend.
-- Sending anything to a customer is a governed act that belongs to a person,
-- and the permission constraint on ai_agents is what makes that true rather
-- than merely intended.
--
-- Their channels are only the three this platform can actually reach.
-- WhatsApp, Telegram, SMS and social messaging have no table, no service and
-- no credential here, and the channel constraint refuses them.
--
-- All are registered CONFIGURED with no runs and no stored performance
-- figures. What each has done is counted from lead_follow_ups and
-- ai_agent_runs by founder_sales_agent_totals.

INSERT INTO public.ai_agents
  (agent_key, name, purpose, specialization, capability, lifecycle, permissions,
   region, market, languages, territory, channels, working_hours, system_prompt, status)
VALUES
  ('sales-india', 'India Sales Agent', 'Coordinates sales activity across India. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'India', 'India', ARRAY['en','hi']::text[], 'India', ARRAY['email','internal_message','lead_followup']::text[], 'IST business hours', 'You work leads and opportunities recorded for India. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-middle-east', 'Middle East Sales Agent', 'Coordinates sales activity across GCC and Levant. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'Middle East', 'GCC and Levant', ARRAY['en','ar']::text[], 'GCC and Levant', ARRAY['email','internal_message','lead_followup']::text[], 'GST business hours', 'You work leads and opportunities recorded for GCC and Levant. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-africa', 'Africa Sales Agent', 'Coordinates sales activity across Sub-Saharan and North Africa. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'Africa', 'Sub-Saharan and North Africa', ARRAY['en','fr','ar']::text[], 'Sub-Saharan and North Africa', ARRAY['email','internal_message','lead_followup']::text[], 'WAT/EAT business hours', 'You work leads and opportunities recorded for Sub-Saharan and North Africa. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-southeast-asia', 'Southeast Asia Sales Agent', 'Coordinates sales activity across ASEAN markets. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'Southeast Asia', 'ASEAN markets', ARRAY['en','id','ms']::text[], 'ASEAN markets', ARRAY['email','internal_message','lead_followup']::text[], 'ICT business hours', 'You work leads and opportunities recorded for ASEAN markets. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-europe', 'Europe Sales Agent', 'Coordinates sales activity across EU and UK. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'Europe', 'EU and UK', ARRAY['en','de','fr','es']::text[], 'EU and UK', ARRAY['email','internal_message','lead_followup']::text[], 'CET business hours', 'You work leads and opportunities recorded for EU and UK. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-north-america', 'North America Sales Agent', 'Coordinates sales activity across United States and Canada. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'North America', 'United States and Canada', ARRAY['en','es','fr']::text[], 'United States and Canada', ARRAY['email','internal_message','lead_followup']::text[], 'ET business hours', 'You work leads and opportunities recorded for United States and Canada. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-latin-america', 'Latin America Sales Agent', 'Coordinates sales activity across Mexico, Brazil and the Southern Cone. Qualifies, follows up, drafts and recommends; sends nothing without a person.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'Latin America', 'Mexico, Brazil and the Southern Cone', ARRAY['es','pt','en']::text[], 'Mexico, Brazil and the Southern Cone', ARRAY['email','internal_message','lead_followup']::text[], 'BRT business hours', 'You work leads and opportunities recorded for Mexico, Brazil and the Southern Cone. You answer in the language the enquiry was written in where you can, you never invent a customer detail, and you draft rather than send.', 'active'),
  ('sales-lead-qualification', 'Lead Qualification Agent', 'Scores and qualifies incoming leads against the recorded criteria. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You scores and qualifies incoming leads against the recorded criteria. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-lead-followup', 'Lead Follow-up Agent', 'Tracks due and overdue follow-ups and drafts the next contact. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You tracks due and overdue follow-ups and drafts the next contact. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-outbound-sales', 'Outbound Sales Agent', 'Prepares outbound approaches to recorded prospects. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You prepares outbound approaches to recorded prospects. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-inbound-sales', 'Inbound Sales Agent', 'Handles inbound enquiries and routes them to the right offer. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You handles inbound enquiries and routes them to the right offer. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-demo-booking', 'Demo Booking Agent', 'Arranges product demonstrations against real availability. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You arranges product demonstrations against real availability. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-demo-followup', 'Demo Follow-up Agent', 'Follows up after a demonstration and records the outcome. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You follows up after a demonstration and records the outcome. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-trial-conversion', 'Trial Conversion Agent', 'Works trials towards a decision before they lapse. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works trials towards a decision before they lapse. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-subscription-sales', 'Subscription Sales Agent', 'Sells and renews subscription plans. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You sells and renews subscription plans. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-renewal-sales', 'Renewal Sales Agent', 'Works upcoming renewals and lapse risk. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works upcoming renewals and lapse risk. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-upsell', 'Upsell Agent', 'Identifies and prepares upgrade offers for existing customers. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You identifies and prepares upgrade offers for existing customers. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-cross-sell', 'Cross-sell Agent', 'Identifies complementary products for existing customers. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You identifies complementary products for existing customers. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-enterprise-sales', 'Enterprise Sales Agent', 'Works large accounts with longer decision cycles. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works large accounts with longer decision cycles. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-smb-sales', 'SMB Sales Agent', 'Works small and mid-sized business opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works small and mid-sized business opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-reseller-sales', 'Reseller Sales Agent', 'Supports and grows the reseller channel. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You supports and grows the reseller channel. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-franchise-sales', 'Franchise Sales Agent', 'Works franchise opportunities and applications. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works franchise opportunities and applications. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-partner-sales', 'Partner Sales Agent', 'Works partner-sourced opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works partner-sourced opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-channel-sales', 'Channel Sales Agent', 'Manages channel pipeline and conflict. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You manages channel pipeline and conflict. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-marketplace-sales', 'Marketplace Sales Agent', 'Works marketplace listings and buyer enquiries. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works marketplace listings and buyer enquiries. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-software-sales', 'Software Sales Agent', 'Sells the licensed software catalogue. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You sells the licensed software catalogue. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-saas-sales', 'SaaS Sales Agent', 'Sells hosted subscription products. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You sells hosted subscription products. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-offline-software-sales', 'Offline Software Sales Agent', 'Sells on-premises and offline-capable products. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You sells on-premises and offline-capable products. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-education-sales', 'Education Sales Agent', 'Works education-sector opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works education-sector opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-pos-sales', 'POS Sales Agent', 'Works point-of-sale product opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works point-of-sale product opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-erp-sales', 'ERP Sales Agent', 'Works ERP product opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works ERP product opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-crm-sales', 'CRM Sales Agent', 'Works CRM product opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works CRM product opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-review-management-sales', 'Review Management Sales Agent', 'Sells reputation and review products. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You sells reputation and review products. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-agency-sales', 'Agency Sales Agent', 'Works agency and reseller-of-record opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works agency and reseller-of-record opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-international-sales', 'International Sales Agent', 'Works cross-border opportunities and their constraints. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works cross-border opportunities and their constraints. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-localization-sales', 'Localization Sales Agent', 'Works opportunities requiring localized product or terms. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works opportunities requiring localized product or terms. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-proposal', 'Proposal Agent', 'Prepares proposals from recorded requirements and pricing. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You prepares proposals from recorded requirements and pricing. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-quotation', 'Quotation Agent', 'Prepares quotations from the recorded price list. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You prepares quotations from the recorded price list. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-negotiation-support', 'Sales Negotiation Support Agent', 'Assembles the evidence a negotiation needs. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You assembles the evidence a negotiation needs. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-objection-handling', 'Objection Handling Agent', 'Prepares responses to recorded objections. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You prepares responses to recorded objections. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-customer-reactivation', 'Customer Reactivation Agent', 'Works customers who have gone quiet. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works customers who have gone quiet. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-lost-lead-recovery', 'Lost Lead Recovery Agent', 'Revisits leads recorded as lost. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You revisits leads recorded as lost. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-checkout-recovery', 'Cart and Checkout Recovery Agent', 'Works abandoned checkouts. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works abandoned checkouts. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-referral-sales', 'Referral Sales Agent', 'Works referred opportunities. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works referred opportunities. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-affiliate-sales', 'Affiliate Sales Agent', 'Supports affiliate-sourced sales. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You supports affiliate-sourced sales. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-reseller-recruitment', 'Reseller Recruitment Agent', 'Recruits new resellers. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You recruits new resellers. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-franchise-recruitment', 'Franchise Recruitment Agent', 'Recruits new franchisees. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You recruits new franchisees. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-high-value-lead', 'High-Value Lead Agent', 'Works the highest-value leads on record. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works the highest-value leads on record. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-enterprise-account', 'Enterprise Account Agent', 'Manages named enterprise accounts. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You manages named enterprise accounts. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-customer-expansion', 'Customer Expansion Agent', 'Grows existing accounts. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You grows existing accounts. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-dormant-customer', 'Dormant Customer Agent', 'Works customers with no recent activity. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You works customers with no recent activity. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-sales-analytics', 'Sales Analytics Agent', 'Analyses recorded sales activity and outcomes. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You analyses recorded sales activity and outcomes. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-competitive-intelligence', 'Competitive Sales Intelligence Agent', 'Assembles competitor signals from authorized sources. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You assembles competitor signals from authorized sources. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active'),
  ('sales-regional-sales-intelligence', 'Regional Sales Intelligence Agent', 'Analyses performance by region. Drafts and recommends only.', 'SALES', 'BALANCED', 'CONFIGURED', ARRAY['READ','ANALYZE','RECOMMEND','CREATE']::text[], 'GLOBAL', 'All markets', ARRAY['en']::text[], 'All territories', ARRAY['email','internal_message','lead_followup']::text[], 'Follows the territory it is working', 'You analyses performance by region. You work only from what is recorded, you say when a record is missing rather than assuming it, and you draft rather than send.', 'active')
ON CONFLICT (agent_key) WHERE agent_key IS NOT NULL DO UPDATE SET
  name           = EXCLUDED.name,
  purpose        = EXCLUDED.purpose,
  specialization = EXCLUDED.specialization,
  permissions    = EXCLUDED.permissions,
  region         = EXCLUDED.region,
  market         = EXCLUDED.market,
  languages      = EXCLUDED.languages,
  territory      = EXCLUDED.territory,
  channels       = EXCLUDED.channels,
  working_hours  = EXCLUDED.working_hours,
  system_prompt  = EXCLUDED.system_prompt;
