-- Global registry reference-data layer (additive, backward compatible)
-- Provides the scalable country / language / search-engine vocabulary
-- required so future AI/API/SEO providers can be added purely through
-- registry rows instead of redesigning core schema or business logic.
-- Nothing here modifies or replaces any existing table, module or flow.

CREATE TABLE IF NOT EXISTS public.registry_countries (
  code text PRIMARY KEY,
  name text NOT NULL,
  region text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.registry_languages (
  code text PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.registry_search_engines (
  slug text PRIMARY KEY,
  name text NOT NULL,
  primary_regions text[] NOT NULL DEFAULT '{}',
  has_official_webmaster_api boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.registry_countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registry_languages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registry_search_engines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS registry_countries_read ON public.registry_countries;
CREATE POLICY registry_countries_read ON public.registry_countries FOR SELECT USING (true);
DROP POLICY IF EXISTS registry_languages_read ON public.registry_languages;
CREATE POLICY registry_languages_read ON public.registry_languages FOR SELECT USING (true);
DROP POLICY IF EXISTS registry_search_engines_read ON public.registry_search_engines;
CREATE POLICY registry_search_engines_read ON public.registry_search_engines FOR SELECT USING (true);

INSERT INTO public.registry_countries (code, name, region) VALUES
  ('AF', 'Afghanistan', 'asia'),
  ('AL', 'Albania', 'europe'),
  ('DZ', 'Algeria', 'africa'),
  ('AD', 'Andorra', 'europe'),
  ('AO', 'Angola', 'africa'),
  ('AG', 'Antigua and Barbuda', 'americas'),
  ('AR', 'Argentina', 'americas'),
  ('AM', 'Armenia', 'asia'),
  ('AU', 'Australia', 'oceania'),
  ('AT', 'Austria', 'europe'),
  ('AZ', 'Azerbaijan', 'asia'),
  ('BS', 'Bahamas', 'americas'),
  ('BH', 'Bahrain', 'asia'),
  ('BD', 'Bangladesh', 'asia'),
  ('BB', 'Barbados', 'americas'),
  ('BY', 'Belarus', 'europe'),
  ('BE', 'Belgium', 'europe'),
  ('BZ', 'Belize', 'americas'),
  ('BJ', 'Benin', 'africa'),
  ('BT', 'Bhutan', 'asia'),
  ('BO', 'Bolivia', 'americas'),
  ('BA', 'Bosnia and Herzegovina', 'europe'),
  ('BW', 'Botswana', 'africa'),
  ('BR', 'Brazil', 'americas'),
  ('BN', 'Brunei', 'asia'),
  ('BG', 'Bulgaria', 'europe'),
  ('BF', 'Burkina Faso', 'africa'),
  ('BI', 'Burundi', 'africa'),
  ('CV', 'Cabo Verde', 'africa'),
  ('KH', 'Cambodia', 'asia'),
  ('CM', 'Cameroon', 'africa'),
  ('CA', 'Canada', 'americas'),
  ('CF', 'Central African Republic', 'africa'),
  ('TD', 'Chad', 'africa'),
  ('CL', 'Chile', 'americas'),
  ('CN', 'China', 'asia'),
  ('CO', 'Colombia', 'americas'),
  ('KM', 'Comoros', 'africa'),
  ('CG', 'Congo', 'africa'),
  ('CD', 'Congo (DRC)', 'africa'),
  ('CR', 'Costa Rica', 'americas'),
  ('CI', 'Cote d''Ivoire', 'africa'),
  ('HR', 'Croatia', 'europe'),
  ('CU', 'Cuba', 'americas'),
  ('CY', 'Cyprus', 'europe'),
  ('CZ', 'Czechia', 'europe'),
  ('DK', 'Denmark', 'europe'),
  ('DJ', 'Djibouti', 'africa'),
  ('DM', 'Dominica', 'americas'),
  ('DO', 'Dominican Republic', 'americas'),
  ('EC', 'Ecuador', 'americas'),
  ('EG', 'Egypt', 'africa'),
  ('SV', 'El Salvador', 'americas'),
  ('GQ', 'Equatorial Guinea', 'africa'),
  ('ER', 'Eritrea', 'africa'),
  ('EE', 'Estonia', 'europe'),
  ('SZ', 'Eswatini', 'africa'),
  ('ET', 'Ethiopia', 'africa'),
  ('FJ', 'Fiji', 'oceania'),
  ('FI', 'Finland', 'europe'),
  ('FR', 'France', 'europe'),
  ('GA', 'Gabon', 'africa'),
  ('GM', 'Gambia', 'africa'),
  ('GE', 'Georgia', 'asia'),
  ('DE', 'Germany', 'europe'),
  ('GH', 'Ghana', 'africa'),
  ('GR', 'Greece', 'europe'),
  ('GD', 'Grenada', 'americas'),
  ('GT', 'Guatemala', 'americas'),
  ('GN', 'Guinea', 'africa'),
  ('GW', 'Guinea-Bissau', 'africa'),
  ('GY', 'Guyana', 'americas'),
  ('HT', 'Haiti', 'americas'),
  ('HN', 'Honduras', 'americas'),
  ('HK', 'Hong Kong', 'asia'),
  ('HU', 'Hungary', 'europe'),
  ('IS', 'Iceland', 'europe'),
  ('IN', 'India', 'asia'),
  ('ID', 'Indonesia', 'asia'),
  ('IR', 'Iran', 'asia'),
  ('IQ', 'Iraq', 'asia'),
  ('IE', 'Ireland', 'europe'),
  ('IL', 'Israel', 'asia'),
  ('IT', 'Italy', 'europe'),
  ('JM', 'Jamaica', 'americas'),
  ('JP', 'Japan', 'asia'),
  ('JO', 'Jordan', 'asia'),
  ('KZ', 'Kazakhstan', 'asia'),
  ('KE', 'Kenya', 'africa'),
  ('KI', 'Kiribati', 'oceania'),
  ('KP', 'North Korea', 'asia'),
  ('KR', 'South Korea', 'asia'),
  ('KW', 'Kuwait', 'asia'),
  ('KG', 'Kyrgyzstan', 'asia'),
  ('LA', 'Laos', 'asia'),
  ('LV', 'Latvia', 'europe'),
  ('LB', 'Lebanon', 'asia'),
  ('LS', 'Lesotho', 'africa'),
  ('LR', 'Liberia', 'africa'),
  ('LY', 'Libya', 'africa'),
  ('LI', 'Liechtenstein', 'europe'),
  ('LT', 'Lithuania', 'europe'),
  ('LU', 'Luxembourg', 'europe'),
  ('MO', 'Macao', 'asia'),
  ('MG', 'Madagascar', 'africa'),
  ('MW', 'Malawi', 'africa'),
  ('MY', 'Malaysia', 'asia'),
  ('MV', 'Maldives', 'asia'),
  ('ML', 'Mali', 'africa'),
  ('MT', 'Malta', 'europe'),
  ('MH', 'Marshall Islands', 'oceania'),
  ('MR', 'Mauritania', 'africa'),
  ('MU', 'Mauritius', 'africa'),
  ('MX', 'Mexico', 'americas'),
  ('FM', 'Micronesia', 'oceania'),
  ('MD', 'Moldova', 'europe'),
  ('MC', 'Monaco', 'europe'),
  ('MN', 'Mongolia', 'asia'),
  ('ME', 'Montenegro', 'europe'),
  ('MA', 'Morocco', 'africa'),
  ('MZ', 'Mozambique', 'africa'),
  ('MM', 'Myanmar', 'asia'),
  ('NA', 'Namibia', 'africa'),
  ('NR', 'Nauru', 'oceania'),
  ('NP', 'Nepal', 'asia'),
  ('NL', 'Netherlands', 'europe'),
  ('NZ', 'New Zealand', 'oceania'),
  ('NI', 'Nicaragua', 'americas'),
  ('NE', 'Niger', 'africa'),
  ('NG', 'Nigeria', 'africa'),
  ('MK', 'North Macedonia', 'europe'),
  ('NO', 'Norway', 'europe'),
  ('OM', 'Oman', 'asia'),
  ('PK', 'Pakistan', 'asia'),
  ('PW', 'Palau', 'oceania'),
  ('PS', 'Palestine', 'asia'),
  ('PA', 'Panama', 'americas'),
  ('PG', 'Papua New Guinea', 'oceania'),
  ('PY', 'Paraguay', 'americas'),
  ('PE', 'Peru', 'americas'),
  ('PH', 'Philippines', 'asia'),
  ('PL', 'Poland', 'europe'),
  ('PT', 'Portugal', 'europe'),
  ('QA', 'Qatar', 'asia'),
  ('RO', 'Romania', 'europe'),
  ('RU', 'Russia', 'europe'),
  ('RW', 'Rwanda', 'africa'),
  ('KN', 'Saint Kitts and Nevis', 'americas'),
  ('LC', 'Saint Lucia', 'americas'),
  ('VC', 'Saint Vincent and the Grenadines', 'americas'),
  ('WS', 'Samoa', 'oceania'),
  ('SM', 'San Marino', 'europe'),
  ('ST', 'Sao Tome and Principe', 'africa'),
  ('SA', 'Saudi Arabia', 'asia'),
  ('SN', 'Senegal', 'africa'),
  ('RS', 'Serbia', 'europe'),
  ('SC', 'Seychelles', 'africa'),
  ('SL', 'Sierra Leone', 'africa'),
  ('SG', 'Singapore', 'asia'),
  ('SK', 'Slovakia', 'europe'),
  ('SI', 'Slovenia', 'europe'),
  ('SB', 'Solomon Islands', 'oceania'),
  ('SO', 'Somalia', 'africa'),
  ('ZA', 'South Africa', 'africa'),
  ('SS', 'South Sudan', 'africa'),
  ('ES', 'Spain', 'europe'),
  ('LK', 'Sri Lanka', 'asia'),
  ('SD', 'Sudan', 'africa'),
  ('SR', 'Suriname', 'americas'),
  ('SE', 'Sweden', 'europe'),
  ('CH', 'Switzerland', 'europe'),
  ('SY', 'Syria', 'asia'),
  ('TW', 'Taiwan', 'asia'),
  ('TJ', 'Tajikistan', 'asia'),
  ('TZ', 'Tanzania', 'africa'),
  ('TH', 'Thailand', 'asia'),
  ('TL', 'Timor-Leste', 'asia'),
  ('TG', 'Togo', 'africa'),
  ('TO', 'Tonga', 'oceania'),
  ('TT', 'Trinidad and Tobago', 'americas'),
  ('TN', 'Tunisia', 'africa'),
  ('TR', 'Turkey', 'asia'),
  ('TM', 'Turkmenistan', 'asia'),
  ('TV', 'Tuvalu', 'oceania'),
  ('UG', 'Uganda', 'africa'),
  ('UA', 'Ukraine', 'europe'),
  ('AE', 'United Arab Emirates', 'asia'),
  ('GB', 'United Kingdom', 'europe'),
  ('US', 'United States', 'americas'),
  ('UY', 'Uruguay', 'americas'),
  ('UZ', 'Uzbekistan', 'asia'),
  ('VU', 'Vanuatu', 'oceania'),
  ('VA', 'Vatican City', 'europe'),
  ('VE', 'Venezuela', 'americas'),
  ('VN', 'Vietnam', 'asia'),
  ('YE', 'Yemen', 'asia'),
  ('ZM', 'Zambia', 'africa'),
  ('ZW', 'Zimbabwe', 'africa')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.registry_languages (code, name) VALUES
  ('aa', 'Afar'),
  ('ab', 'Abkhazian'),
  ('af', 'Afrikaans'),
  ('ak', 'Akan'),
  ('sq', 'Albanian'),
  ('am', 'Amharic'),
  ('ar', 'Arabic'),
  ('an', 'Aragonese'),
  ('hy', 'Armenian'),
  ('as', 'Assamese'),
  ('av', 'Avaric'),
  ('ae', 'Avestan'),
  ('ay', 'Aymara'),
  ('az', 'Azerbaijani'),
  ('bm', 'Bambara'),
  ('ba', 'Bashkir'),
  ('eu', 'Basque'),
  ('be', 'Belarusian'),
  ('bn', 'Bengali'),
  ('bi', 'Bislama'),
  ('bs', 'Bosnian'),
  ('br', 'Breton'),
  ('bg', 'Bulgarian'),
  ('my', 'Burmese'),
  ('ca', 'Catalan'),
  ('ch', 'Chamorro'),
  ('ce', 'Chechen'),
  ('ny', 'Chichewa'),
  ('zh', 'Chinese'),
  ('cv', 'Chuvash'),
  ('kw', 'Cornish'),
  ('co', 'Corsican'),
  ('cr', 'Cree'),
  ('hr', 'Croatian'),
  ('cs', 'Czech'),
  ('da', 'Danish'),
  ('dv', 'Divehi'),
  ('nl', 'Dutch'),
  ('dz', 'Dzongkha'),
  ('en', 'English'),
  ('eo', 'Esperanto'),
  ('et', 'Estonian'),
  ('ee', 'Ewe'),
  ('fo', 'Faroese'),
  ('fj', 'Fijian'),
  ('fi', 'Finnish'),
  ('fr', 'French'),
  ('ff', 'Fulah'),
  ('gl', 'Galician'),
  ('ka', 'Georgian'),
  ('de', 'German'),
  ('el', 'Greek'),
  ('gn', 'Guarani'),
  ('gu', 'Gujarati'),
  ('ht', 'Haitian Creole'),
  ('ha', 'Hausa'),
  ('he', 'Hebrew'),
  ('hz', 'Herero'),
  ('hi', 'Hindi'),
  ('ho', 'Hiri Motu'),
  ('hu', 'Hungarian'),
  ('ia', 'Interlingua'),
  ('id', 'Indonesian'),
  ('ie', 'Interlingue'),
  ('ga', 'Irish'),
  ('ig', 'Igbo'),
  ('ik', 'Inupiaq'),
  ('io', 'Ido'),
  ('is', 'Icelandic'),
  ('it', 'Italian'),
  ('iu', 'Inuktitut'),
  ('ja', 'Japanese'),
  ('jv', 'Javanese'),
  ('kl', 'Kalaallisut'),
  ('kn', 'Kannada'),
  ('kr', 'Kanuri'),
  ('ks', 'Kashmiri'),
  ('kk', 'Kazakh'),
  ('km', 'Khmer'),
  ('ki', 'Kikuyu'),
  ('rw', 'Kinyarwanda'),
  ('ky', 'Kyrgyz'),
  ('kv', 'Komi'),
  ('kg', 'Kongo'),
  ('ko', 'Korean'),
  ('ku', 'Kurdish'),
  ('kj', 'Kuanyama'),
  ('la', 'Latin'),
  ('lb', 'Luxembourgish'),
  ('lg', 'Ganda'),
  ('li', 'Limburgish'),
  ('ln', 'Lingala'),
  ('lo', 'Lao'),
  ('lt', 'Lithuanian'),
  ('lu', 'Luba-Katanga'),
  ('lv', 'Latvian'),
  ('gv', 'Manx'),
  ('mk', 'Macedonian'),
  ('mg', 'Malagasy'),
  ('ms', 'Malay'),
  ('ml', 'Malayalam'),
  ('mt', 'Maltese'),
  ('mi', 'Maori'),
  ('mr', 'Marathi'),
  ('mh', 'Marshallese'),
  ('mn', 'Mongolian'),
  ('na', 'Nauru'),
  ('nv', 'Navajo'),
  ('nd', 'North Ndebele'),
  ('ne', 'Nepali'),
  ('ng', 'Ndonga'),
  ('nb', 'Norwegian Bokmal'),
  ('nn', 'Norwegian Nynorsk'),
  ('no', 'Norwegian'),
  ('ii', 'Sichuan Yi'),
  ('nr', 'South Ndebele'),
  ('oc', 'Occitan'),
  ('oj', 'Ojibwe'),
  ('cu', 'Church Slavic'),
  ('om', 'Oromo'),
  ('or', 'Oriya'),
  ('os', 'Ossetian'),
  ('pa', 'Punjabi'),
  ('pi', 'Pali'),
  ('fa', 'Persian'),
  ('pl', 'Polish'),
  ('ps', 'Pashto'),
  ('pt', 'Portuguese'),
  ('qu', 'Quechua'),
  ('rm', 'Romansh'),
  ('rn', 'Rundi'),
  ('ro', 'Romanian'),
  ('ru', 'Russian'),
  ('sa', 'Sanskrit'),
  ('sc', 'Sardinian'),
  ('sd', 'Sindhi'),
  ('se', 'Northern Sami'),
  ('sm', 'Samoan'),
  ('sg', 'Sango'),
  ('sr', 'Serbian'),
  ('gd', 'Scottish Gaelic'),
  ('sn', 'Shona'),
  ('si', 'Sinhala'),
  ('sk', 'Slovak'),
  ('sl', 'Slovenian'),
  ('so', 'Somali'),
  ('st', 'Southern Sotho'),
  ('es', 'Spanish'),
  ('su', 'Sundanese'),
  ('sw', 'Swahili'),
  ('ss', 'Swati'),
  ('sv', 'Swedish'),
  ('ta', 'Tamil'),
  ('te', 'Telugu'),
  ('tg', 'Tajik'),
  ('th', 'Thai'),
  ('ti', 'Tigrinya'),
  ('bo', 'Tibetan'),
  ('tk', 'Turkmen'),
  ('tl', 'Tagalog'),
  ('tn', 'Tswana'),
  ('to', 'Tongan'),
  ('tr', 'Turkish'),
  ('ts', 'Tsonga'),
  ('tt', 'Tatar'),
  ('tw', 'Twi'),
  ('ty', 'Tahitian'),
  ('ug', 'Uyghur'),
  ('uk', 'Ukrainian'),
  ('ur', 'Urdu'),
  ('uz', 'Uzbek'),
  ('ve', 'Venda'),
  ('vi', 'Vietnamese'),
  ('vo', 'Volapuk'),
  ('wa', 'Walloon'),
  ('cy', 'Welsh'),
  ('wo', 'Wolof'),
  ('fy', 'Western Frisian'),
  ('xh', 'Xhosa'),
  ('yi', 'Yiddish'),
  ('yo', 'Yoruba'),
  ('za', 'Zhuang'),
  ('zu', 'Zulu')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.registry_search_engines (slug, name, primary_regions, has_official_webmaster_api) VALUES
  ('google', 'Google', ARRAY['global']::text[], true),
  ('bing', 'Bing', ARRAY['global']::text[], true),
  ('yandex', 'Yandex', ARRAY['russia','cis']::text[], true),
  ('naver', 'Naver', ARRAY['south-korea']::text[], true),
  ('baidu', 'Baidu', ARRAY['china']::text[], true),
  ('brave-search', 'Brave Search', ARRAY['global']::text[], true),
  ('duckduckgo', 'DuckDuckGo', ARRAY['global']::text[], true),
  ('yahoo-japan', 'Yahoo! Japan', ARRAY['japan']::text[], false),
  ('seznam', 'Seznam.cz', ARRAY['czechia']::text[], false),
  ('ecosia', 'Ecosia', ARRAY['global']::text[], false),
  ('sogou', 'Sogou', ARRAY['china']::text[], false),
  ('so-360', '360 Search (So.com)', ARRAY['china']::text[], false),
  ('qwant', 'Qwant', ARRAY['france','europe']::text[], false),
  ('startpage', 'Startpage', ARRAY['global']::text[], false)
ON CONFLICT (slug) DO NOTHING;

